name: Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          bin/build.sh
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
